name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # SSH into the EC2 instance and run the deployment commands
        ssh -o StrictHostKeyChecking=no -i key.pem ${USERNAME}@${HOST} << 'EOF'
          cd /home/ubuntu/claws-mcc
          
          # remove any local changes that might interefere with git pull
          git reset --hard

          # pull the latest changes
          git pull

          # check if pnpm is installed and install it if not
            if ! command -v pnpm &> /dev/null
            then
                # Install pnpm
                curl -fsSL https://get.pnpm.io/install.sh | sh -
                source /home/ubuntu/.bashrc
            fi
          
          # install root deps
          pnpm install
          pnpm run build
          
          # install client deps
          cd client
          pnpm install
          pnpm run build
          cd ..
          
          # restart backend and frontend
          pm2 restart all
          sudo systemctl restart nginx
        EOF
