name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install root dependencies
      run: npm i

    - name: Install client dependencies and build client
      run: |
        cd client
        npm i
        npm run build
        cd ..

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$KEY" > key.pem
        chmod 400 key.pem
        scp -o StrictHostKeyChecking=no -i key.pem -r client/build/* ${USERNAME}@${HOST}:/var/www/claws-mcc/build
        ssh -o StrictHostKeyChecking=no -i key.pem ${USERNAME}@${HOST} '
          cd /home/ubuntu/claws-mcc/client
          git pull
          npm ci
          pm2 restart all
          sudo systemctl restart nginx
        '