name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Prepare SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        # SSH into the EC2 instance and run the deployment commands
        ssh -o StrictHostKeyChecking=no -i key.pem ${USERNAME}@${HOST} << 'EOF'
          # Ensure the working directory is the project directory
          cd /home/ubuntu/claws-mcc
          
          # Pull the latest changes
          git pull
          
          # Install root dependencies and build if necessary
          npm install
          npm run build
          
          # Install client dependencies, build the client
          cd client
          npm install
          npm run build
          
          # Navigate back to the root project directory if needed
          cd ..
          
          # Restart the application and web server
          pm2 restart all
          sudo systemctl restart nginx
        EOF
